spring.application.name=APIAcuicultura

spring.datasource.url=jdbc:postgresql://localhost:5432/acuicultura
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none